"""Every drafted skill-position player must resolve to a price and a tier.

This is the check that matters on draft day. A name Sleeper spells differently
from ETR or FantasyPros doesn't raise — it quietly resolves to $0, which shrinks
the expected-value denominator and skews every inflation number. So we walk a
real draft's worth of names through the backend's own lookup and assert each one
lands on the row it should.

Names come from <year>/sleeper_draft_names.csv, a snapshot of the 192 picks in
Sleeper mock 1392544863014121472. Players the sources genuinely don't cover are
listed in <year>/unpriced_players.csv and excused here; both files are
regenerated by backend/build_player_mappings.py.

Targets the enhanced FastAPI backend, which is what npm run backend starts.
"""

import os
import sys
import unittest

import pandas as pd

sys.path.append(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'backend'))

from build_year_data import POSITIONS  # noqa: E402
import fastapi_backend_enhanced as backend  # noqa: E402


class TestPlayerMappings(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.data_dir = backend.LATEST_DATA_DIR
        cls.year = backend.LATEST_YEAR
        cls.manager = backend.DataManager()
        cls.auction_lookup = cls.manager._data_cache['player_auction_lookup']
        cls.mappings = cls.manager._data_cache['player_mappings']

        fixture = os.path.join(cls.data_dir, 'sleeper_draft_names.csv')
        if not os.path.exists(fixture):
            raise unittest.SkipTest(f"No sleeper_draft_names.csv in {cls.data_dir}")
        picks = pd.read_csv(fixture)
        cls.picks = [
            (str(row['Sleeper Name']), str(row['Position']), int(row['Sale Price']))
            for _, row in picks.iterrows()
            if str(row['Position']) in POSITIONS
        ]

        unpriced_path = os.path.join(cls.data_dir, 'unpriced_players.csv')
        unpriced = pd.read_csv(unpriced_path) if os.path.exists(unpriced_path) else pd.DataFrame(
            columns=['Sleeper Name', 'Missing From'])
        cls.no_price = {str(r['Sleeper Name']) for _, r in unpriced.iterrows()
                        if 'auction value' in str(r['Missing From'])}
        cls.no_tier = {str(r['Sleeper Name']) for _, r in unpriced.iterrows()
                       if 'tier' in str(r['Missing From'])}

    def test_fixture_covers_a_full_draft(self):
        self.assertGreaterEqual(len(self.picks), 100, "Fixture looks truncated")

    def test_every_pick_lands_on_an_auction_row(self):
        """Resolution, not price: ETR legitimately values a long tail at $0."""
        missing = []
        for name, position, _ in self.picks:
            if name in self.no_price or name in self.auction_lookup:
                continue
            mapped = self.mappings.get(name, {}).get('auction_name')
            if mapped not in self.auction_lookup:
                missing.append(f"{name} ({position})")
        self.assertEqual(
            [], missing,
            f"{len(missing)} drafted players never reach an auction-value row in {self.year} — "
            f"add a mapping, an alias, or an unpriced_players.csv entry: {missing}"
        )

    def test_every_pick_resolves_to_a_tier(self):
        missing = []
        for name, position, _ in self.picks:
            if name in self.no_tier:
                continue
            _, tier = self.manager.get_player_info_optimized(name, position)
            if tier == 'N/A' or pd.isna(tier):
                missing.append(f"{name} ({position})")
        self.assertEqual([], missing, f"{len(missing)} drafted players have no tier in {self.year}: {missing}")

    def test_lookup_returns_the_source_value(self):
        """get_player_info_optimized must reach the same dollars as a manual lookup."""
        wrong = []
        for name, position, _ in self.picks:
            if name in self.no_price:
                continue
            source_name = name if name in self.auction_lookup else self.mappings.get(name, {}).get('auction_name')
            if source_name not in self.auction_lookup:
                continue  # covered by test_every_pick_lands_on_an_auction_row
            expected = backend.to_dollars(self.auction_lookup[source_name]['value'])
            actual, _ = self.manager.get_player_info_optimized(name, position)
            if backend.to_dollars(actual) != expected:
                wrong.append(f"{name} ({position}): got ${backend.to_dollars(actual):.0f}, source says ${expected:.0f}")
        self.assertEqual([], wrong, f"{len(wrong)} lookups disagree with the source: {wrong}")

    def test_inflation_uses_the_mapping_aware_lookup(self):
        """The inflation denominator must match a hand-rolled sum over the same picks.

        Regression guard: the inflation calculation used to hit the auction dict
        with the raw Sleeper name, so every anomaly scored $0. On the 2026 mock
        that hid $129 of expected value and flipped overall inflation's sign.
        """
        draft, expected_total = [], 0.0
        for index, (name, position, price) in enumerate(self.picks):
            first, _, last = name.partition(' ')
            draft.append({
                'pick_no': index + 1,
                'draft_slot': (index % 12) + 1,
                'metadata': {'first_name': first, 'last_name': last,
                             'position': position, 'amount': str(price)},
            })
            value, _ = self.manager.get_player_info_optimized(name, position)
            expected_total += backend.to_dollars(value)

        result = self.manager._calculate_inflation_rates_optimized(draft)
        self.assertAlmostEqual(
            expected_total, result['total_expected'], places=2,
            msg="Inflation's expected-value pool disagrees with a per-player lookup — "
                "something is bypassing get_player_info_optimized again."
        )

    def test_whole_board_tiers_are_not_lost_to_spelling(self):
        """Every player on the All Players board must be tiered, or genuinely unranked.

        The tests above only walk the 192 names in one draft. The All Players tab
        shows the entire auction board, so a spelling drift on a player nobody
        drafted in that mock stays invisible until someone nominates them live and
        the tier column comes up blank. A missing tier is only acceptable when
        FantasyPros doesn't rank the player at all — never when both sources have
        them under different spellings.
        """
        from build_year_data import normalize_name

        tier_lookups = self.manager._data_cache['positional_tier_lookups']
        ranked = {}
        for position in POSITIONS:
            for name in tier_lookups[position]:
                ranked.setdefault(normalize_name(name), (position, name))

        mismatched = []
        for _, row in self.manager._data_cache['auction_values_df'].iterrows():
            position = str(row['Position'])
            if position not in POSITIONS:
                continue  # K and DST are never tiered
            name = str(row['Player'])
            _, tier = self.manager.get_player_info_optimized(name, position)
            if str(tier) not in ('N/A', 'nan'):
                continue
            match = ranked.get(normalize_name(name))
            if match:
                mismatched.append(f"{name} ({position}) -> FantasyPros has {match[1]!r} as {match[0]}")

        self.assertEqual(
            [], mismatched,
            f"{len(mismatched)} players are in both sources but spelled differently, so the "
            f"board shows them with no tier: {mismatched}"
        )

    def test_mapping_targets_all_exist(self):
        """Nothing in player_name_mappings.csv should point at a name that isn't there."""
        tier_lookups = self.manager._data_cache['positional_tier_lookups']
        mappings_df = self.manager._data_cache['mappings_df']
        dangling = []
        for _, row in mappings_df.iterrows():
            sleeper_name = str(row['Sleeper Name'])
            position = str(row['Position'])
            if str(row['Auction Value Name']) not in self.auction_lookup and sleeper_name not in self.no_price:
                dangling.append(f"{sleeper_name} -> auction {row['Auction Value Name']!r}")
            if str(row['Tier Name']) not in tier_lookups.get(position, {}) and sleeper_name not in self.no_tier:
                dangling.append(f"{sleeper_name} -> tier {row['Tier Name']!r}")
        self.assertEqual([], dangling, f"Mappings point at names that don't exist: {dangling}")


if __name__ == '__main__':
    unittest.main()
